apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: flower
  name: flower-controller
  namespace: celery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: flower
    spec:
      containers:
      - image: sahandha/flower:py3.5.3
        name: flower
        resources:
          limits:
            cpu: 100m
